#Should the highlight be always hidden behind the blocks
always-hide-behind-blocks: true
repeat-animations:
  #The repeat name can be any, as long as there no two repeats with same name
  '1':
    animation: test
    repeat-every: 30
animations:
  'test':
    #The world in which this animation will be shown
    world: 'world'
    #From what distance will the animation be visible. Optional, if not specified, it will be 4096
    view-distance-squared: 4096
    frames:
      #This is the number of the tick on which the desired highlight is performed after animation start
      0:
        #The highlight is specified in the format:
        #x y z, color, transparency (0-255), text, time (How long will this highlight last in milliseconds)
        - "0 64 0, #37db97, 100, , 800"
        - "1 64 0, #37db97, 100, , 800"
        - "2 64 0, #37db97, 100, , 800"
      3:
        - "0 64 1, #3dbf89, 130, , 800"
        - "1 64 1, #3dbf89, 130, , 800"
        - "2 64 1, #3dbf89, 130, , 800"
      6:
        - "0 64 2, #3a9972, 160, , 800"
        - "1 64 2, #3a9972, 160, , 800"
        - "2 64 2, #3a9972, 160, , 800"
      9:
        - "0 64 3, #28805b, 190, , 800"
        - "1 64 3, #28805b, 190, , 800"
        - "2 64 3, #28805b, 190, , 800"
      12:
        - "0 64 4, #20543e, 220, , 800"
        - "1 64 4, #20543e, 220, , 800"
        - "2 64 4, #20543e, 220, , 800"
  'text':
    world: 'world'
    frames:
      0:
        - "5 64 5, #37db97, 0, &c&lHello, 10000"